import { signals } from '@/lib/data';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import Link from 'next/link';
import { ArrowRight } from 'lucide-react';

export function SignalsPanel() {
  const latestSignals = signals.slice(0, 5);

  const getBadgeVariant = (type: 'Buy' | 'Sell' | 'Hold'): 'success' | 'destructive' | 'secondary' => {
    if (type === 'Buy') return 'success';
    if (type === 'Sell') return 'destructive';
    return 'secondary';
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Recent Signals</CardTitle>
        <CardDescription>The latest 5 signals generated by our system.</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {latestSignals.map((signal) => (
            <div key={signal.id} className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <Badge variant={getBadgeVariant(signal.type)} className="w-16 justify-center">
                  {signal.type}
                </Badge>
                <div>
                  <p className="font-semibold">{signal.pair}</p>
                  <p className="text-sm text-muted-foreground">
                    {new Date(signal.timestamp).toLocaleTimeString()}
                  </p>
                </div>
              </div>
              <Button variant="ghost" size="icon" asChild>
                <Link href={`/signals/${signal.id}`}>
                  <ArrowRight className="h-4 w-4" />
                </Link>
              </Button>
            </div>
          ))}
        </div>
        <Button variant="outline" className="mt-6 w-full" asChild>
          <Link href="/signals">View All Signals</Link>
        </Button>
      </CardContent>
    </Card>
  );
}
